  columns:
    - name: product_id
      dataType: Int
    - name: name
      dataType: String
    - name: price
      dataType: Int
  rows:
    - [201, Laptop, 1200]
    - [202, Smartphone, 800]
    - [203, Tablet, 600]
    - [204, Monitor, 300]
